### ISSUE TITLE
Icons not showing

### ISSUE THREAD

**Issue by zalapeach** [TheNaoX/dotfiles#2]
Hi dude

I still using your dotfiles, but I was wondering how to show the icons on the terminal, I run the .install.sh file and everything works properly. Only the icons are not showing properly. Can you tell me how to fix this issue?

Thanks in advance.

**Comment by TheNaoX** [comment]
Did you install the fonts that are in the `fonts/` folder? You need to do that and select the any of those, also if your terminal does not support emojis there's a chance they are going to look like that

**Comment by zalapeach** [comment]
Yes, I installed the fonts, so the problem might be that my shell doesn't support the emojis. I will continue researching about this.

Thanks for your help
